tools:
  exceptions: https://sentry.io/organizations/dcsil/issues/?project=6146694
  logging: https://service.us2.sumologic.com/ui/?appName=blockcomet-dev
  ci: https://github.com/dcsil/blockcomet-dev/actions

services:
  production: https://blockcomet-dev.herokuapp.com/

docs:
  getting_started: https://github.com/dcsil/blockcomet-dev/blob/main/README.md
  
commands:
  bootstrap: bin/bootstrap
  server: app/server/setup_server
  webapp: app/client/start_app
  database: https://cloud.mongodb.com/v2/6229cfaf4efbde230c214e23#metrics/replicaSet/6229d0e1f0bcbd1bf33b7cd0/explorer/blockcomet_users
  test: bin/test
