tools:
  exceptions: https://sentry.io/organizations/dcsil/issues/?project=6146694
  logging: https://service.us2.sumologic.com/ui/?appName=blockcomet-dev
  ci: https://github.com/dcsil/blockcomet-dev/actions

services:
  production: https://blockcomet.nn.r.appspot.com/
  production_server: https://blockcometapi-6dkam7pfeq-uc.a.run.app/ 

docs:
  getting_started: https://github.com/dcsil/blockcomet-dev/blob/main/README.md
  
commands:
  bootstrap: bin/bootstrap
  server: app/server/setup_server
  webapp: app/client/start_app
  database: bin/mongodb
  test: bin/test
