name: Code Coverage Reporter
on: push
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: coverage run -m pytest
        coverageLocations: |
          ${{github.workspace}}/client/coverage/lcov.info:lcov
          ${{github.workspace}}/server/coverage/lcov.info:lcov