name: Deploy to Google Cloud

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          version: master
          credentials: ${{secrets.GCP_SA_KEY}}
          flags: --no-cache
          deliverables: app/server/app.yaml