name: Deploy Backend to Google Cloud

# Controls when the workflow will run
on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'
        service_account_key: '${{ secrets.GCP_SA_KEY }}'

    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'app/server/app.yaml'