name: PyTest
on: push

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ${{github.workspace}}/app/server

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10' 
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Check python versions
        run: |
          pwd
          python --version

      - name: Turning off virtualenv
        run: |
          pwd
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest and publish coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: coverage run -m pytest