name: PyTest
on: push

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
          
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: cd into server
        run: cd app/server

      - name: Turning off virtualenv
        run: poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest
