name: PyTest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: cd into server
        run: |
          cd app/server
          pwd
          poetry config --list

      - name: Check python versions
        run: |
          pwd
          python --version

      - name: Turning off virtualenv
        run: |
          pwd
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: |
          cd app/server
          poetry install
      
      # - name: Setup Nodejs and npm
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "14"

      # - name: Setup yarn
      #   run: npm install -g yarn

      # - name: Install modules
      #   run: |
      #     cd app/client
      #     yarn
      
      - name: Check PWD
        run: pwd

      # - name: Test with pytest and publish coverage
      #   uses: paambaati/codeclimate-action@v2.7.1
      #   env:
      #     CC_TEST_REPORTER_ID: f664ec478b07e02ec20197f90b89f38e8085d2083f6ca81a346046b53d2876ed
      #   with:
      #     coverageCommand: bash ./bin/test_coverage
      #     coverageLocations: |
      #       ${{github.workspace}}/client/coverage/lcov.info:lcov
      #       ${{github.workspace}}/server/xml_coverage.xml:clover

      - name: Run Pytest
        run: |
          cd app/server
          poetry run pytest tests --cov-report xml --cov server

      - name: Test & publish coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}